### ISSUE TITLE
Error when trying to start service with 'yez' terminal command

### ISSUE THREAD

**Issue by nezuky** [krasimir/yez#16]
>***npm install -g yez***

```
/usr/local/bin/yez -> /usr/local/lib/node_modules/yez/node/index.js

> ws@0.4.32 install /usr/local/lib/node_modules/yez/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o

> electron-prebuilt@0.37.6 postinstall /usr/local/lib/node_modules/yez/node_modules/electron-prebuilt
> node install.js

Downloading electron-v0.37.6-darwin-x64.zip
[============================================>] 100.0% of 41.2 MB (3.83 MB/s)
+ yez@2.1.0
added 204 packages in 23.756s
```

>***yez***

```
/usr/local/lib/node_modules/yez/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;`
                                         ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/yez/node_modules/socket.io/lib/store.js:35:42)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/yez/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:612:30)
```

(macOS Sierra)

**Comment by chip** [comment]
I'm getting the same error with node 8.9.0. However, it works with 4.8.7. However, I can't edit with vim, so I'm limited to basic shell commands I guess. Still a really interesting idea, though. 👍

**Comment by muygalan** [comment]
Did anyone manage to come up with a solution to this error? I'm having the same problem on Windows 10. Thanks.
